user_name = input("Input your name: ")
user_age = input("Input your age: ")
user_height = input("Input your height in meters: ")
user_gender = input("Input True if your gender Male: ")
print(user_name, user_age, user_gender, user_height)
user_age = int(user_age)
user_height = float(user_height)
user_gender = bool(user_gender)
print(type(user_name), type(user_age), type(user_height), type(user_gender))